os: linux
dist: trusty
language: python
services: docker

env:
  global:
  - BASE=fastsolve/desktop:base
  matrix:
  - XVFB=1
  - XVFB=0

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  # and the base image is older than this commit
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since `docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/$1/g" -p`) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] || [[ "$XVFB" != "1" ]] ||
     (docker build --tag fastsolve/desktop:latest . &&
      docker push fastsolve/desktop &&
      touch success)'
  # Trigger build of the latest branch of numgeom-desktop
  - '[[ ! -f success ]] ||
     (git clone -b ci-master https://$GIT_USER:$GIT_TOKEN@github.com/numgeom/docker-desktop.git numgeom 2> /dev/null &&
      cd numgeom &&
      git commit --allow-empty -m "Trigger compilation." &&
      git push && cd ..)'
  - ./fastsolve_desktop.py -d -n -t latest && docker stop $(docker ps -q)
  - ./fastsolve_jupyter.py -d -n -t latest && docker stop $(docker ps -q)
  - docker images
