language: python

services: docker

env:
  global:
    - BRANCH=dev-env
    - BASE=fastsolve/desktop:base

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e config)" ]] ||
     (docker build --tag fastsolve/desktop:$BRANCH . &&
      docker push fastsolve/desktop:$BRANCH &&
      touch success)'
# Trigger build of ci-dev branch of fastsolve-desktop
  - '[[ ! -f success ]] ||
       (git clone -b ci-dev https://$GIT_USER:$GIT_TOKEN@github.com/fastsolve/docker-desktop.git ci-dev &&
       cd ci-dev &&
       git commit --allow-empty -m "Trigger compilation." &&
       git push)'
# Trigger build of ci-debug branch of fastsolve-desktop
  - '[[ ! -f success ]] ||
     (git clone -b ci-debug --depth 1 https://$GIT_USER:$GIT_TOKEN@github.com/fastsolve/docker-desktop.git ci-debug 2> /dev/null &&
      cd ci-debug &&
      git commit --allow-empty -m "Trigger compilation." &&
      git push && cd ..)'
# Test scripts
  - '[[ ! -f success ]] ||
    (git clone -b master https://github.com/fastsolve/docker-desktop.git master &&
     master/fastsolve_desktop.py -d -n -t dev-env && docker stop $(docker ps -q) &&
     master/fastsolve_jupyter.py -d -n -t dev-env && docker stop $(docker ps -q))'
  - docker images
