os: linux
dist: trusty
language: python
services: docker

env:
  - XVFB=1
  - XVFB=0

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - 'docker build --tag fastsolve/desktop:cuda . &&
     docker push fastsolve/desktop:cuda &&
     touch success'
  # Test scripts
  - git clone https://github.com/fastsolve/docker-desktop master
  - master/fastsolve_desktop.py -d -n -t cuda && docker stop $(docker ps -q)
  - master/fastsolve_jupyter.py -d -n -t cuda && docker stop $(docker ps -q)
  - docker images
