language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - echo $MATLAB_URL > url
  - 'docker build --tag fastsolve/desktop:dev . &&
     docker push fastsolve/desktop:dev &&
     touch success'
# Trigger build of dev branch of numgeom-desktop
  - '[[ ! -f success ]] ||
     (git clone -b dev https://$GIT_USER:$GIT_TOKEN@github.com/numgeom/docker-desktop.git numgeom 2> /dev/null &&
      cd numgeom &&
      git commit --allow-empty -m "Trigger compilation." &&
      git push && cd ..)'
# Test startup scripts and trigger build of dev branch
  - '[[ ! -f success ]] ||
       (git clone -b dev https://$GIT_USER:$GIT_TOKEN@github.com/fastsolve/docker-desktop.git dev &&
       cd dev &&
       git commit --allow-empty -m "Trigger compilation." &&
       git push)'
# Test scripts
  - '[[ ! -f success ]] ||
    (git clone -b master https://github.com/fastsolve/docker-desktop.git master 2> /dev/null &&
     master/fastsolve_desktop.py -d -n -t dev && docker stop $(docker ps -q) &&
     master/fastsolve_jupyter.py -d -n -t dev && docker stop $(docker ps -q))'
  - docker images
